pool:
  vmImage: 'ubuntu-16.04'
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '11.14.0'
    displayName: 'Node.jsバージョン指定'
  - script: |
      yarn install
    displayName: 'yarn install'
  - script: |
      sudo apt install -y fonts-takao
    displayName: 'システムにフォントをインストール'
  - script: |
      yarn test
    displayName: 'テスト'
  - script: |
      yarn prod
    displayName: 'プロダクション環境向けビルド'
