pool:
  vmImage: 'ubuntu-16.04'
steps:
  - task: Cache@2
    inputs:
      key: 'node_modules | "$(Agent.OS)"'
      restoreKeys: node_modules
      path: node_modules
    displayName: node_modules
  - task: NodeTool@0
    inputs:
      versionSpec: '14.2.0'
    displayName: 'Node.jsバージョン指定'
  - script: |
      yarn install
    displayName: 'yarn install'
  - script: |
      yarn run lint
    displayName: 'Lint'
  - script: |
      sudo apt install -y fonts-takao
    displayName: 'システムにフォントをインストール'
  - script: |
      yarn test
    displayName: 'テスト'
  - script: |
      yarn prod
    displayName: 'プロダクション環境向けビルド'
