PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX imas: <https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#>
PREFIX imasrdf: <https://sparql.crssnky.xyz/imasrdf/RDFs/detail/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX math: <http://www.w3.org/2005/xpath-functions/math#>
PREFIX xsd: <https://www.w3.org/TR/xmlschema11-2/#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT (sample(?n)as ?liveName) (sample(?sD)as ?liveDate) (sample(?loc)as ?liveLocation) (group_concat(?a)as ?liveActor)
WHERE {
  ?s rdf:type imas:Live;
       schema:startDate ?sD;
       schema:name ?n;
       schema:location ?loc;
       schema:actor ?a
  filter(?sD>="@@DATE@@"^^<http://www.w3.org/2001/XMLSchema#date>)
}group by ?s order by ?liveDate
